import { StyleSheet, Platform } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#1a1410",
  },
  contentContainer: {
    padding: 20,
    paddingBottom: 40,
  },
  contentContainerWithBottomButtons: {
    paddingBottom: 20,
  },
  fixedBottomButtons: {
    backgroundColor: "#1a1410",
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: Platform.OS === "ios" ? 34 : 20,
    borderTopWidth: 1,
    borderTopColor: "#3b2c1a",
    alignItems: "center",
  },
  progressBar: {
    flexDirection: "row",
    justifyContent: "center",
    marginBottom: 30,
    gap: 8,
  },
  progressDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: "#3b2c1a",
    borderWidth: 1,
    borderColor: "#FFD700",
  },
  progressDotActive: {
    backgroundColor: "#FFD700",
    transform: [{ scale: 1.3 }],
  },
  progressDotComplete: {
    backgroundColor: "#4CAF50",
    borderColor: "#4CAF50",
  },
  stageContainer: {
    alignItems: "center",
    flex: 1,
    width: "100%",
  },
  notationContainer: {
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 10,
    marginVertical: 16,
    alignItems: "center",
  },
  stageTitle: {
    fontSize: 28,
    fontWeight: "bold",
    color: "#FFD700",
    textAlign: "center",
    marginBottom: 20,
    fontFamily: Platform.OS === "ios" ? "Baskerville" : "serif",
  },
  subtitle: {
    fontSize: 16,
    color: "#fffbe6",
    marginBottom: 20,
  },
  noteDisplay: {
    fontSize: 64,
    fontWeight: "bold",
    color: "#FFD700",
    marginVertical: 20,
  },
  instruction: {
    fontSize: 18,
    color: "#fffbe6",
    textAlign: "center",
    lineHeight: 28,
    marginVertical: 20,
    paddingHorizontal: 10,
  },
  hint: {
    fontSize: 14,
    color: "#999",
    textAlign: "center",
    marginTop: 10,
    fontStyle: "italic",
  },
  summaryToggleButton: {
    backgroundColor: "rgba(255, 215, 0, 0.1)",
    borderWidth: 1,
    borderColor: "#FFD700",
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: 16,
    marginTop: 15,
    alignSelf: "center",
  },
  summaryToggleText: {
    color: "#FFD700",
    fontSize: 14,
  },
  summaryContainer: {
    backgroundColor: "rgba(255, 215, 0, 0.1)",
    borderWidth: 1,
    borderColor: "#FFD700",
    borderRadius: 12,
    padding: 16,
    marginTop: 15,
    position: "relative",
  },
  summaryCloseButton: {
    position: "absolute",
    top: 4,
    right: 4,
    padding: 12,
    zIndex: 10,
  },
  summaryCloseText: {
    color: "#999",
    fontSize: 18,
  },
  summaryTitle: {
    color: "#FFD700",
    fontSize: 16,
    fontWeight: "bold",
    marginBottom: 10,
    textAlign: "center",
  },
  summaryItem: {
    color: "#fffbe6",
    fontSize: 13,
    marginVertical: 3,
    paddingLeft: 8,
  },
  bold: {
    fontWeight: "bold",
    color: "#FFD700",
  },
  italic: {
    fontStyle: "italic",
  },
  primaryButton: {
    backgroundColor: "#4CAF50",
    paddingHorizontal: 32,
    paddingVertical: 16,
    borderRadius: 12,
    marginVertical: 10,
    minWidth: 200,
    alignItems: "center",
  },
  primaryButtonText: {
    color: "#FFF",
    fontSize: 18,
    fontWeight: "600",
  },
  secondaryButton: {
    backgroundColor: "transparent",
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: "#FFD700",
    marginVertical: 10,
  },
  secondaryButtonText: {
    color: "#FFD700",
    fontSize: 16,
    fontWeight: "500",
  },
  completionButtons: {
    width: "100%",
    gap: 10,
    marginTop: 8,
  },
  homeButton: {
    backgroundColor: "transparent",
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#666",
    alignItems: "center",
  },
  homeButtonText: {
    color: "#888",
    fontSize: 16,
    fontWeight: "500",
  },
  backTextButton: {
    paddingVertical: 12,
    paddingHorizontal: 16,
  },
  backTextButtonText: {
    color: "#888",
    fontSize: 16,
    fontWeight: "500",
  },
  buttonDisabled: {
    opacity: 0.6,
  },
  buttonRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: 10,
    marginTop: 20,
  },
  buttonColumn: {
    flexDirection: "column",
    alignItems: "center",
    gap: 12,
    marginTop: 20,
    width: "100%",
  },
  ratingContainer: {
    flexDirection: "row",
    justifyContent: "center",
    gap: 8,
    marginVertical: 20,
    flexWrap: "wrap",
  },
  ratingButton: {
    alignItems: "center",
    padding: 10,
    borderRadius: 12,
    backgroundColor: "#2d2419",
    borderWidth: 1,
    borderColor: "#3b2c1a",
    minWidth: 60,
  },
  ratingEmoji: {
    fontSize: 32,
    marginBottom: 4,
  },
  ratingLabel: {
    fontSize: 11,
    color: "#a09080",
    textAlign: "center",
  },
  playScreenContainer: {
    flex: 1,
    width: "100%",
    justifyContent: "space-between",
  },
  playScreenContent: {
    alignItems: "center",
    flex: 1,
  },
  feedbackContainer: {
    height: 50,
    justifyContent: "center",
    alignItems: "center",
  },
  bottomButtonContainer: {
    alignItems: "center",
    paddingBottom: 20,
    marginTop: 20,
  },
  successText: {
    fontSize: 24,
    color: "#4CAF50",
    fontWeight: "bold",
    marginVertical: 15,
  },
  warningText: {
    fontSize: 16,
    color: "#FF9800",
    marginTop: 10,
  },
  errorBanner: {
    backgroundColor: "#FF6B6B",
    padding: 15,
    borderRadius: 8,
    marginBottom: 20,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  errorText: {
    color: "#FFF",
    fontSize: 14,
  },
  dismissText: {
    color: "#FFF",
    fontWeight: "bold",
  },
  focusCard: {
    backgroundColor: "#2a1f15",
    borderRadius: 16,
    padding: 20,
    marginVertical: 20,
    borderWidth: 1,
    borderColor: "#FFD700",
    width: "100%",
    maxWidth: 400,
  },
  focusCardTitle: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#FFD700",
    marginBottom: 10,
    textAlign: "center",
  },
  focusCardDescription: {
    fontSize: 16,
    color: "#fffbe6",
    marginBottom: 15,
    textAlign: "center",
  },
  focusCardCue: {
    fontSize: 14,
    color: "#999",
    fontStyle: "italic",
    textAlign: "center",
  },
  focusCardMini: {
    backgroundColor: "#2a1f15",
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 16,
    marginBottom: 15,
    borderWidth: 1,
    borderColor: "#FFD700",
  },
  focusCardMiniTitle: {
    fontSize: 14,
    fontWeight: "600",
    color: "#FFD700",
    textAlign: "center",
  },
  ratingSummary: {
    marginVertical: 15,
    width: "100%",
    maxWidth: 300,
  },
  ratingSummaryRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#3b2c1a",
  },
  ratingSummaryCard: {
    fontSize: 16,
    color: "#fffbe6",
  },
  ratingSummaryEmoji: {
    fontSize: 24,
  },
  successMessage: {
    fontSize: 16,
    color: "#4CAF50",
    textAlign: "center",
    marginVertical: 15,
  },
  noteDisplaySmall: {
    fontSize: 28,
    fontWeight: "bold",
    color: "#FFD700",
    marginBottom: 15,
    textAlign: "center",
  },
  stepsContainer: {
    width: "100%",
    maxWidth: 400,
  },
  stepRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    backgroundColor: "#2a1f15",
    borderRadius: 12,
    padding: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: "#3b2c1a",
  },
  stepDisabled: {
    opacity: 0.5,
  },
  stepIcon: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: "#1a140d",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  stepEmoji: {
    fontSize: 24,
  },
  stepContent: {
    flex: 1,
  },
  stepLabel: {
    fontSize: 16,
    fontWeight: "600",
    color: "#FFD700",
    marginBottom: 6,
  },
  stepButton: {
    backgroundColor: "#FFD700",
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 8,
    alignSelf: "flex-start",
    marginTop: 6,
  },
  stepButtonText: {
    color: "#1a140d",
    fontWeight: "600",
    fontSize: 14,
  },
  stepDone: {
    color: "#4CAF50",
    fontWeight: "600",
    fontSize: 14,
  },
  stepLocked: {
    color: "#666",
    fontStyle: "italic",
    fontSize: 13,
  },
  stepHint: {
    color: "#a09080",
    fontSize: 13,
    marginBottom: 6,
  },
  successTextSmall: {
    color: "#4CAF50",
    fontSize: 14,
    fontWeight: "600",
    marginVertical: 4,
  },
  // Compact Focus Practice Panel Styles
  focusPracticePanel: {
    backgroundColor: "#2a1f15",
    borderRadius: 16,
    padding: 12,
    width: "100%",
    maxWidth: 400,
    borderWidth: 2,
    borderColor: "#FFD700",
  },
  focusBanner: {
    backgroundColor: "#3b2c1a",
    borderRadius: 10,
    padding: 10,
    marginBottom: 8,
    borderWidth: 2,
    borderColor: "#FF6B35",
    alignItems: "center",
  },
  focusBannerLabel: {
    fontSize: 10,
    fontWeight: "bold",
    color: "#FF6B35",
    letterSpacing: 2,
    marginBottom: 2,
  },
  focusBannerTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#FFD700",
    marginBottom: 4,
  },
  focusBannerCue: {
    fontSize: 12,
    color: "#fffbe6",
    fontStyle: "italic",
    textAlign: "center",
    lineHeight: 16,
  },
  focusNoteRow: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 8,
    gap: 6,
  },
  focusNoteLabel: {
    fontSize: 13,
    color: "#a09080",
  },
  focusMiniNote: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#FFD700",
  },
  focusTabBar: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 8,
    gap: 4,
  },
  focusTab: {
    flex: 1,
    alignItems: "center",
    paddingVertical: 6,
    paddingHorizontal: 3,
    borderRadius: 6,
    backgroundColor: "#1a140d",
    borderWidth: 1,
    borderColor: "#3b2c1a",
  },
  focusTabActive: {
    backgroundColor: "#3b2c1a",
    borderColor: "#FFD700",
  },
  focusTabDone: {
    backgroundColor: "#1a2a1a",
    borderColor: "#4CAF50",
  },
  focusTabEmoji: {
    fontSize: 16,
    marginBottom: 1,
  },
  focusTabLabel: {
    fontSize: 9,
    color: "#a09080",
    textAlign: "center",
  },
  focusTabLabelActive: {
    color: "#FFD700",
    fontWeight: "600",
  },
  stepContentArea: {
    alignItems: "center",
    minHeight: 180,
    justifyContent: "center",
    paddingVertical: 10,
  },
  stepContentAreaCompact: {
    alignItems: "center",
    height: 175,
    justifyContent: "center",
    paddingVertical: 4,
    gap: 6,
  },
  stepInstruction: {
    fontSize: 13,
    color: "#fffbe6",
    textAlign: "center",
    marginBottom: 8,
  },
  focusReminder: {
    fontSize: 12,
    color: "#999",
    fontStyle: "italic",
    textAlign: "center",
    marginBottom: 12,
    paddingHorizontal: 10,
  },
  focusReminderBold: {
    fontSize: 13,
    color: "#FF6B35",
    fontWeight: "600",
    textAlign: "center",
    marginBottom: 12,
  },
  focusActionButton: {
    backgroundColor: "#FFD700",
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    marginTop: 10,
  },
  focusActionButtonText: {
    color: "#1a140d",
    fontWeight: "600",
    fontSize: 16,
  },
  focusNavBar: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 16,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: "#3b2c1a",
  },
  focusNavButton: {
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#a09080",
  },
  focusNavButtonDisabled: {
    opacity: 0.3,
  },
  focusNavButtonText: {
    color: "#a09080",
    fontSize: 14,
  },
  focusNavButtonPrimary: {
    backgroundColor: "#4CAF50",
    paddingVertical: 10,
    paddingHorizontal: 24,
    borderRadius: 8,
  },
  focusNavButtonPrimaryText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "600",
  },
  staffVisual: {
    marginVertical: 30,
    alignItems: "center",
    width: 280,
    paddingVertical: 10,
  },
  ledgerLineDemo: {
    marginVertical: 20,
    alignItems: "center",
    width: 280,
    paddingVertical: 10,
    position: "relative",
  },
  ledgerLineDemoRow: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "flex-start",
    gap: 40,
    marginVertical: 20,
    width: 280,
    paddingVertical: 10,
  },
  ledgerLineDemoColumn: {
    alignItems: "center",
    position: "relative",
    width: 80,
  },
  staffLineShort: {
    width: 80,
    height: 2,
    backgroundColor: "#FFD700",
    marginVertical: 8,
  },
  noteDemoCircleSmall: {
    position: "absolute",
    width: 20,
    height: 14,
    borderRadius: 10,
    backgroundColor: "#FFD700",
    transform: [{ rotate: "-15deg" }],
    left: "35%",
    zIndex: 10,
  },
  ledgerLineSmall: {
    width: 50,
    height: 2,
    backgroundColor: "#FFD700",
    marginVertical: 8,
  },
  noteDemoCircle: {
    position: "absolute",
    width: 24,
    height: 16,
    borderRadius: 12,
    backgroundColor: "#FFD700",
    transform: [{ rotate: "-15deg" }],
    left: "45%",
    zIndex: 10,
  },
  ledgerLineExplorer: {
    position: "absolute",
    width: 50,
    height: 2,
    backgroundColor: "#FFD700",
    left: "40%",
    zIndex: 5,
  },
  staffLine: {
    width: "100%",
    height: 2,
    backgroundColor: "#FFD700",
    marginVertical: 8,
  },
  noteVisualContainer: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 40,
    marginVertical: 30,
  },
  noteCircleFilled: {
    width: 40,
    height: 32,
    borderRadius: 20,
    backgroundColor: "#FFD700",
    transform: [{ rotate: "-15deg" }],
  },
  noteCircleHollow: {
    width: 40,
    height: 32,
    borderRadius: 20,
    borderWidth: 3,
    borderColor: "#FFD700",
    backgroundColor: "transparent",
    transform: [{ rotate: "-15deg" }],
  },
  staffWithNoteVisual: {
    marginVertical: 30,
    alignItems: "center",
    width: 280,
    paddingVertical: 10,
    position: "relative",
  },
  noteOnLine: {
    position: "absolute",
    width: 24,
    height: 16,
    borderRadius: 12,
    backgroundColor: "#FFD700",
    transform: [{ rotate: "-15deg" }],
    zIndex: 10,
  },
  noteInSpace: {
    position: "absolute",
    width: 24,
    height: 16,
    borderRadius: 12,
    backgroundColor: "#FFD700",
    transform: [{ rotate: "-15deg" }],
    zIndex: 10,
  },
  pitchExplorerStaff: {
    marginTop: 20,
    marginBottom: 50,
    alignItems: "center",
    width: 280,
    height: 100,
    position: "relative",
    justifyContent: "space-between",
    paddingVertical: 5,
  },
  pitchExplorerNote: {
    position: "absolute",
    left: "45%",
    width: 22,
    height: 15,
    borderRadius: 11,
    backgroundColor: "#FFD700",
    transform: [{ rotate: "-15deg" }],
    zIndex: 10,
  },
  pitchExplorerNoteName: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#FFD700",
    marginBottom: 20,
  },
  pitchExplorerControls: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 15,
  },
  pitchExplorerButton: {
    backgroundColor: "transparent",
    borderWidth: 2,
    borderColor: "#FFD700",
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 10,
  },
  pitchExplorerButtonDisabled: {
    opacity: 0.3,
  },
  pitchExplorerButtonText: {
    color: "#FFD700",
    fontSize: 16,
    fontWeight: "600",
  },
  pitchExplorerPlayButton: {
    backgroundColor: "#4CAF50",
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 10,
  },
  pitchExplorerPlayButtonText: {
    color: "#FFF",
    fontSize: 16,
    fontWeight: "600",
  },
  combinedExplorerStaff: {
    marginTop: 20,
    marginBottom: 50,
    alignItems: "center",
    width: 280,
    height: 100,
    position: "relative",
    justifyContent: "space-between",
    paddingVertical: 5,
  },
  combinedExplorerControls: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 15,
    marginBottom: 15,
  },
  combinedAccidentalButtons: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 10,
  },
  funFact: {
    fontSize: 20,
    color: "#4CAF50",
    fontWeight: "bold",
    marginBottom: 15,
  },
  staffInfectionImage: {
    width: 300,
    height: 250,
    marginVertical: 15,
    borderRadius: 10,
  },
  bassClefImage: {
    width: 240,
    height: 160,
  },
  imageWhiteBubble: {
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 20,
    marginVertical: 20,
  },
  clefSymbol: {
    fontSize: 100,
    color: "#FFD700",
    marginVertical: 20,
  },
  accidentalRow: {
    flexDirection: "row",
    gap: 40,
    marginVertical: 20,
  },
  accidentalBox: {
    alignItems: "center",
  },
  accidentalSymbol: {
    fontSize: 60,
    color: "#FFD700",
  },
  accidentalName: {
    fontSize: 16,
    color: "#fffbe6",
    marginTop: 5,
  },
  accidentalExplorerStaff: {
    marginVertical: 20,
    alignItems: "center",
    width: 280,
    height: 100,
    position: "relative",
    justifyContent: "space-between",
    paddingVertical: 5,
  },
  accidentalExplorerNote: {
    position: "absolute",
    left: "50%",
    marginLeft: -11,
    top: "42.5%",
    width: 22,
    height: 15,
    borderRadius: 11,
    backgroundColor: "#FFD700",
    transform: [{ rotate: "-15deg" }],
    zIndex: 10,
  },
  accidentalOnStaff: {
    position: "absolute",
    left: "50%",
    marginLeft: -38,
    top: "28%",
    fontSize: 40,
    color: "#FFD700",
    zIndex: 10,
  },
  flatOnStaff: {
    position: "absolute",
    left: "50%",
    marginLeft: -38,
    top: "26%",
    fontSize: 40,
    color: "#FFD700",
    zIndex: 10,
  },
  sharpOnStaff: {
    position: "absolute",
    left: "50%",
    marginLeft: -38,
    top: "28%",
    fontSize: 40,
    color: "#FFD700",
    zIndex: 10,
  },
  accidentalExplorerControls: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 20,
    marginTop: 20,
  },
  accidentalExplorerButton: {
    backgroundColor: "transparent",
    borderWidth: 2,
    borderColor: "#FFD700",
    width: 60,
    height: 60,
    borderRadius: 30,
    justifyContent: "center",
    alignItems: "center",
  },
  accidentalExplorerButtonActive: {
    backgroundColor: "rgba(255, 215, 0, 0.3)",
  },
  accidentalExplorerButtonText: {
    color: "#FFD700",
    fontSize: 32,
  },
  staffWithNote: {
    flexDirection: "row",
    alignItems: "center",
    marginVertical: 30,
    paddingHorizontal: 20,
  },
  staffClef: {
    fontSize: 60,
    color: "#FFD700",
    marginRight: 10,
  },
  staffLinesContainer: {
    position: "relative",
    flex: 1,
  },
  staffLineNote: {
    color: "#FFD700",
    fontSize: 14,
    marginVertical: 6,
    letterSpacing: 1,
  },
  noteHead: {
    position: "absolute",
    left: "50%",
    flexDirection: "row",
    alignItems: "center",
    transform: [{ translateX: -15 }],
  },
  noteHeadText: {
    fontSize: 36,
    color: "#4CAF50",
  },
  noteAccidental: {
    fontSize: 24,
    color: "#4CAF50",
    marginLeft: -10,
    marginTop: -15,
  },
});

export default styles;
